spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SIMONE
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  application:
    name: ecommerce-API
  datasource:
    password: 'Database510!'
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/ecommerceDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  auth:
    converter:
      resource-id: simone-rest-api
      principle-attribute: preferred_username

server:
  port: 8081

  ssl:
    key-alias: spring-https
    key-store: classpath:simon.p12
    key-store-type: PKCS12
    key-store-password: password


